/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ffb4ab",
        "surface-container-highest": "#27272a",
        "surface-container-lowest": "#09090b",
        "primary-fixed": "#e0d7ff",
        "secondary-container": "#00a6e0",
        "on-secondary-fixed-variant": "#004c69",
        "surface": "#12121a",
        "surface-glass": "rgba(255, 255, 255, 0.05)",
        "border-glass": "rgba(255, 255, 255, 0.1)",
        "outline-variant": "#3f3f46",
        "surface-container-high": "#18181b",
        "on-secondary-fixed": "#001e2c",
        "inverse-on-surface": "#f4f4f5",
        "on-surface": "#fafafa",
        "primary": "#8b5cf6",
        "primary-variant": "#7C3AED",
        "primary-soft": "rgba(139, 92, 246, 0.15)",
        "inverse-primary": "#5b21b6",
        "background": "#080810",
        "on-primary-fixed-variant": "#5b21b6",
        "on-tertiary-fixed": "#1c1c16",
        "error-container": "#93000a",
        "on-primary-container": "#e0d7ff",
        "surface-container-low": "#111113",
        "on-secondary-container": "#00374d",
        "surface-bright": "#27272a",
        "on-error-container": "#ffdad6",
        "surface-container": "#141417",
        "surface-dim": "#09090b",
        "on-background": "#fafafa",
        "primary-container": "#8b5cf6",
        "inverse-surface": "#fafafa",
        "tertiary-container": "#b5b2a9",
        "tertiary-fixed": "#e6e2d8",
        "on-surface-variant": "#a1a1aa",
        "tertiary": "#d1cdc4",
        "secondary-fixed": "#c4e7ff",
        "outline": "#71717a",
        "surface-tint": "#8b5cf6",
        "on-tertiary-container": "#46453d",
        "surface-variant": "#27272a",
        "on-tertiary": "#32312a",
        "secondary": "#7bd0ff",
        "tertiary-fixed-dim": "#cac6bd",
        "on-secondary": "#00354a",
        "on-primary-fixed": "#2e1065",
        "primary-fixed-dim": "#a78bfa",
        "on-primary": "#ffffff",
        "on-error": "#690005",
        "secondary-fixed-dim": "#7bd0ff",
        "on-tertiary-fixed-variant": "#484740"
      },
      fontFamily: {
        "headline": ["Playfair Display", "serif"],
        "body": ["Lora", "serif"],
        "label": ["Inter", "sans-serif"],
        "serif": ["Newsreader", "serif"],
        "mono": ["IBM Plex Mono", "monospace"],
        "sans": ["Inter", "system-ui", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "1rem", 
        "lg": "2rem", 
        "xl": "3rem", 
        "2xl": "1.5rem",
        "full": "9999px"
      },
      animation: {
        "fade-in": "fadeIn 0.3s ease-in-out",
        "slide-up": "slideUp 0.3s ease-out",
        "pulse-soft": "pulseSoft 2s ease-in-out infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        pulseSoft: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.7" },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
};
